window.HOTEL_QUEST_CONFIG = {
  sheetEndpoint: "https://script.google.com/macros/s/AKfycbx67q0-_uv5QwpPZOsLMZH_azVNIhbGnV3j7FYvN3R0kA9llkdJhbigPivIEFWS1I8V3w/exec",
  hotelName: "Green Line Batumi",
  settings: {
    currentWeather: "sun",
    maxAttempts: 3,
    finishTitle: "Все хранители найдены",
    finishSuccess: "Отличный результат! Вы собрали всех хранителей отеля.",
    finishSupport: "Квест завершен. Не все загадки покорились, но коллекция собрана.",
    nameBlockList: [
      "дурак", "идиот", "бред", "test", "asdf", "qwerty",
      "хуй", "хуила", "хуёк", "хуя", "пидор", "пидар", "пидр",
      "педик", "педрил", "ебан", "ебать", "ебла", "ебуч",
      "бля", "бляд", "бляди", "срать", "сран", "гандон", "гондон",
      "гавно", "говн", "мудак", "мудил", "залуп", "дроч",
      "пизда", "пизд", "сука", "сук", "уёб", "урод", "дерьм",
      "лох", "чмо", "жопа", "попа", "задница", "хрен",
      "fuck", "shit", "bitch", "ass", "dick", "cunt", "crap",
      "bastard", "damn", "whore", "slut", "fag", "moron", "retard"
    ],
    prizeInfo: "",
    registrationWarning: "",
    primaryColor: "#29771e",
    logoUrl: "",
    roomDigits: 3
  },
  rooms: [
    "101",
    "102",
    "103",
    "104",
    "201",
    "202",
    "203",
    "204",
    "301",
    "302",
    "303",
    "304"
  ],
  characters: [
    {
      id: "lobby",
      name: "Люмен",
      place: "Лобби",
      color: "#2364aa",
      x: 50,
      y: 20,
      enabled: true,
      active: true,
      weatherRule: "any",
      availableFrom: "",
      availableTo: "",
      foundPoints: 10,
      attemptPoints: [30, 20, 10],
      riddle: "Я встречаю гостей первым, храню ключи и улыбки. Где я?",
      answers: ["ресепшен", "reception", "стойка регистрации", "лобби"],
      image: "",
      imageSolved: "",
      hintType: "text",
      hintText: "Я в лобби, подойди ко мне!",
      hintFoundText: "Ты уже встретил меня!",
      hintAudio: ""
    },
    {
      id: "cafe",
      name: "Мира",
      place: "Кафе",
      color: "#d1663f",
      x: 26,
      y: 43,
      enabled: true,
      active: true,
      weatherRule: "any",
      availableFrom: "",
      availableTo: "",
      foundPoints: 10,
      attemptPoints: [30, 20, 10],
      riddle: "Здесь утро пахнет кофе, а разговоры становятся теплее за маленьким столиком.",
      answers: ["кафе", "coffee", "кофе", "кофейня"],
      image: "",
      imageSolved: "",
      hintType: "text",
      hintText: "Я в кафе, загляни туда!",
      hintFoundText: "Ты меня уже нашёл!",
      hintAudio: ""
    },
    {
      id: "pool",
      name: "Ори",
      place: "Бассейн",
      color: "#2a8c82",
      x: 74,
      y: 43,
      enabled: true,
      active: true,
      weatherRule: "sun",
      availableFrom: "",
      availableTo: "",
      foundPoints: 10,
      attemptPoints: [30, 20, 10],
      riddle: "Я отражаю потолок, шепчу водой и жду тех, кто хочет поплавать.",
      answers: ["бассейн", "pool", "вода"],
      image: "",
      imageSolved: "",
      hintType: "text",
      hintText: "Я у бассейна, приходи в солнечный день!",
      hintFoundText: "Ты меня уже нашёл!",
      hintAudio: ""
    },
    {
      id: "garden",
      name: "Флора",
      place: "Сад",
      color: "#6f8f3d",
      x: 28,
      y: 76,
      enabled: true,
      active: true,
      weatherRule: "rain",
      availableFrom: "",
      availableTo: "",
      foundPoints: 10,
      attemptPoints: [30, 20, 10],
      riddle: "Здесь слышны листья, пахнет землей, а дорожка ведет между зеленью.",
      answers: ["сад", "garden", "двор", "зелень"],
      image: "",
      imageSolved: "",
      hintType: "text",
      hintText: "Я в саду, иди под дождём!",
      hintFoundText: "Ты меня уже нашёл!",
      hintAudio: ""
    },
    {
      id: "stairs",
      name: "Степ",
      place: "Лестница",
      color: "#7a5cba",
      x: 72,
      y: 76,
      enabled: true,
      active: true,
      weatherRule: "any",
      availableFrom: "",
      availableTo: "",
      foundPoints: 10,
      attemptPoints: [30, 20, 10],
      riddle: "Я не лифт, но тоже поднимаю выше. Мои ступени знают путь между этажами.",
      answers: ["лестница", "stairs", "ступени"],
      image: "",
      imageSolved: "",
      hintType: "text",
      hintText: "Я на лестнице, поднимись!",
      hintFoundText: "Ты меня уже нашёл!",
      hintAudio: ""
    }
  ]
};